//+------------------------------------------------------------------+
//|                                                  TrendCrossEA.mq5 |
//|                        Generated by MetaQuotes Language Editor |
//|                                      Copyright 2025, Your Name |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, Your Name"
#property link      "https://www.yourwebsite.com"
#property version   "1.00"

//--- Input parameters
input group "Risk Management"
input double RiskPercent = 1.0;       // Risk Percent per Trade (%)
input bool   TPDynamic = true;        // Dynamic Take Profit
input double FixedTP_Ratio = 1.5;     // Fixed TP Ratio (Risk:Reward)

input group "Indicator Parameters"
input int    FastMA = 10;             // Fast MA Period
input int    SlowMA = 30;             // Slow MA Period
input int    ATRPeriod = 14;          // ATR Period

//--- Global variables
int fastMAHandle, slowMAHandle, atrHandle;
double fastMABuffer[], slowMABuffer[], atrBuffer[];
datetime lastBarTime = 0;
MqlTick currentTick;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Initialize indicator handles
   fastMAHandle = iMA(_Symbol, PERIOD_CURRENT, FastMA, 0, MODE_SMA, PRICE_CLOSE);
   slowMAHandle = iMA(_Symbol, PERIOD_CURRENT, SlowMA, 0, MODE_SMA, PRICE_CLOSE);
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   
   if(fastMAHandle == INVALID_HANDLE || slowMAHandle == INVALID_HANDLE || atrHandle == INVALID_HANDLE)
   {
      Print("Error creating indicator handles");
      return(INIT_FAILED);
   }
   
   //--- Set buffer arrays
   ArraySetAsSeries(fastMABuffer, true);
   ArraySetAsSeries(slowMABuffer, true);
   ArraySetAsSeries(atrBuffer, true);
   
   Print("EA initialized successfully on ", _Symbol, " timeframe: ", EnumToString(Period()));
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   //--- Release indicator handles
   if(fastMAHandle != INVALID_HANDLE) IndicatorRelease(fastMAHandle);
   if(slowMAHandle != INVALID_HANDLE) IndicatorRelease(slowMAHandle);
   if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
   
   Print("EA deinitialized");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check for new bar
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;
   
   //--- Get current tick
   if(!SymbolInfoTick(_Symbol, currentTick))
   {
      Print("Error getting tick data");
      return;
   }
   
   //--- Copy indicator values
   if(CopyBuffer(fastMAHandle, 0, 0, 3, fastMABuffer) < 3)
   {
      Print("Error copying Fast MA buffer");
      return;
   }
   
   if(CopyBuffer(slowMAHandle, 0, 0, 3, slowMABuffer) < 3)
   {
      Print("Error copying Slow MA buffer");
      return;
   }
   
   if(CopyBuffer(atrHandle, 0, 0, 3, atrBuffer) < 3)
   {
      Print("Error copying ATR buffer");
      return;
   }
   
   //--- Debug info
   Print("Fast MA[0]: ", fastMABuffer[0], " Slow MA[0]: ", slowMABuffer[0]);
   Print("ATR[0]: ", atrBuffer[0], " ATR[1]: ", atrBuffer[1]);
   
   //--- Check trading conditions
   CheckForTradingSignals();
   
   //--- Manage dynamic TP if enabled
   if(TPDynamic) ManageDynamicTP();
}

//+------------------------------------------------------------------+
//| Check for trading signals                                        |
//+------------------------------------------------------------------+
void CheckForTradingSignals()
{
   //--- Get current volume and compare with previous
   long currentVolume = iVolume(_Symbol, PERIOD_CURRENT, 0);
   long previousVolume = iVolume(_Symbol, PERIOD_CURRENT, 1);
   
   //--- Check for Long signal (Golden Cross)
   if(fastMABuffer[1] <= slowMABuffer[1] && fastMABuffer[0] > slowMABuffer[0]) // Golden Cross
   {
      Print("Golden Cross detected!");
      Print("Volume: Current=", currentVolume, " Previous=", previousVolume);
      
      // Check ATR for strong bullish trend (current ATR > previous ATR)
      if(atrBuffer[0] > atrBuffer[1])
      {
         if(currentVolume > previousVolume)
         {
            Print("Conditions met for LONG: ATR bullish and volume increasing");
            // Calculate stop loss (below crossover point)
            double stopLoss = slowMABuffer[0] - atrBuffer[0];
            OpenPosition(ORDER_TYPE_BUY, stopLoss);
         }
         else
         {
            Print("Volume condition not met for LONG");
         }
      }
      else
      {
         Print("ATR condition not met for LONG: ATR[0]=", atrBuffer[0], " ATR[1]=", atrBuffer[1]);
      }
   }
   
   //--- Check for Short signal (Death Cross)
   if(fastMABuffer[1] >= slowMABuffer[1] && fastMABuffer[0] < slowMABuffer[0]) // Death Cross
   {
      Print("Death Cross detected!");
      Print("Volume: Current=", currentVolume, " Previous=", previousVolume);
      
      // Check ATR for strong bearish trend (current ATR > previous ATR)
      if(atrBuffer[0] > atrBuffer[1])
      {
         if(currentVolume > previousVolume)
         {
            Print("Conditions met for SHORT: ATR bullish and volume increasing");
            // Calculate stop loss (above crossover point)
            double stopLoss = slowMABuffer[0] + atrBuffer[0];
            OpenPosition(ORDER_TYPE_SELL, stopLoss);
         }
         else
         {
            Print("Volume condition not met for SHORT");
         }
      }
      else
      {
         Print("ATR condition not met for SHORT: ATR[0]=", atrBuffer[0], " ATR[1]=", atrBuffer[1]);
      }
   }
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                      |
//+------------------------------------------------------------------+
double CalculateLotSize(double stopLossDistance, double entryPrice, ENUM_ORDER_TYPE orderType)
{
   //--- Get account balance
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   if(balance <= 0)
   {
      Print("Error: Invalid account balance");
      return 0;
   }
   
   //--- Calculate risk amount in account currency
   double riskAmount = balance * (RiskPercent / 100.0);
   
   //--- Get symbol info
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   
   if(tickSize <= 0 || tickValue <= 0 || point <= 0 || lotStep <= 0)
   {
      Print("Error: Invalid symbol parameters");
      return 0;
   }
   
   //--- Calculate money risk per lot
   double moneyRiskPerLot = (stopLossDistance / point) * tickValue * lotStep;
   
   if(moneyRiskPerLot <= 0)
   {
      Print("Error: Money risk per lot <= 0");
      return 0;
   }
   
   //--- Calculate lot size
   double lots = riskAmount / moneyRiskPerLot;
   lots = MathFloor(lots / lotStep) * lotStep;
   
   //--- Check min/max limits
   if(lots < minLot) lots = minLot;
   if(lots > maxLot) lots = maxLot;
   
   Print("Lot calculation: Balance=", balance, 
         " RiskAmount=", riskAmount, 
         " StopLossDist=", stopLossDistance,
         " MoneyRiskPerLot=", moneyRiskPerLot,
         " CalculatedLots=", lots);
   
   return lots;
}

//+------------------------------------------------------------------+
//| Open trading position                                            |
//+------------------------------------------------------------------+
void OpenPosition(ENUM_ORDER_TYPE orderType, double stopLoss)
{
   //--- Check if we already have a position
   if(PositionSelect(_Symbol))
   {
      Print("Position already exists for ", _Symbol);
      return;
   }
   
   //--- Calculate entry price
   double entryPrice = (orderType == ORDER_TYPE_BUY) ? currentTick.ask : currentTick.bid;
   
   //--- Calculate stop loss distance
   double stopLossDistance = MathAbs(entryPrice - stopLoss);
   
   //--- Calculate lot size
   double lotSize = CalculateLotSize(stopLossDistance, entryPrice, orderType);
   if(lotSize <= 0)
   {
      Print("Error: Invalid lot size");
      return;
   }
   
   //--- Calculate take profit
   double takeProfit = 0;
   if(!TPDynamic)
   {
      if(orderType == ORDER_TYPE_BUY)
         takeProfit = entryPrice + (stopLossDistance * FixedTP_Ratio);
      else if(orderType == ORDER_TYPE_SELL)
         takeProfit = entryPrice - (stopLossDistance * FixedTP_Ratio);
   }
   
   //--- Prepare trade request
   MqlTradeRequest request;
   MqlTradeResult result;
   ZeroMemory(request);
   ZeroMemory(result);
   
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = lotSize;
   request.type = orderType;
   request.price = entryPrice;
   request.sl = stopLoss;
   
   // Only set TP if not dynamic
   if(!TPDynamic && takeProfit > 0)
      request.tp = takeProfit;
   else
      request.tp = 0;
   
   request.deviation = 10;
   request.magic = 12345;
   request.type_filling = ORDER_FILLING_FOK;
   request.type_time = ORDER_TIME_GTC;
   
   //--- Send order
   Print("Sending order: Type=", EnumToString(orderType),
         " Price=", entryPrice,
         " SL=", stopLoss,
         " TP=", request.tp,
         " Lots=", lotSize);
   
   ResetLastError();
   if(!OrderSend(request, result))
   {
      Print("OrderSend failed. Error code: ", GetLastError());
      return;
   }
   
   //--- Check result
   if(result.retcode == TRADE_RETCODE_DONE)
   {
      Print("Order opened successfully! Ticket: ", result.order);
   }
   else
   {
      Print("Order failed. Retcode: ", result.retcode, 
            " Comment: ", result.comment);
   }
}

//+------------------------------------------------------------------+
//| Manage dynamic take profit                                       |
//+------------------------------------------------------------------+
void ManageDynamicTP()
{
   //--- Check existing positions
   if(PositionSelect(_Symbol))
   {
      long ticket = PositionGetInteger(POSITION_TICKET);
      ENUM_POSITION_TYPE posType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      
      Print("Managing position: Ticket=", ticket, " Type=", EnumToString(posType));
      
      //--- Copy indicator values for signal check
      if(CopyBuffer(fastMAHandle, 0, 0, 2, fastMABuffer) < 2 ||
         CopyBuffer(slowMAHandle, 0, 0, 2, slowMABuffer) < 2)
      {
         Print("Error copying buffers for dynamic TP");
         return;
      }
      
      //--- Check for opposite signal
      bool closeSignal = false;
      
      if(posType == POSITION_TYPE_BUY)
      {
         // Check for death cross (opposite signal for long position)
         if(fastMABuffer[0] < slowMABuffer[0])
         {
            Print("Death cross detected - closing LONG position");
            closeSignal = true;
         }
      }
      else if(posType == POSITION_TYPE_SELL)
      {
         // Check for golden cross (opposite signal for short position)
         if(fastMABuffer[0] > slowMABuffer[0])
         {
            Print("Golden cross detected - closing SHORT position");
            closeSignal = true;
         }
      }
      
      //--- Close position if opposite signal detected
      if(closeSignal)
      {
         MqlTradeRequest request;
         MqlTradeResult result;
         ZeroMemory(request);
         ZeroMemory(result);
         
         double volume = PositionGetDouble(POSITION_VOLUME);
         double closePrice = (posType == POSITION_TYPE_BUY) ? currentTick.bid : currentTick.ask;
         
         request.action = TRADE_ACTION_DEAL;
         request.symbol = _Symbol;
         request.volume = volume;
         request.type = (posType == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;
         request.price = closePrice;
         request.deviation = 10;
         request.magic = 12345;
         request.position = PositionGetInteger(POSITION_TICKET);
         request.type_filling = ORDER_FILLING_FOK;
         request.type_time = ORDER_TIME_GTC;
         
         Print("Closing position: Type=", EnumToString(request.type),
               " Price=", closePrice,
               " Volume=", volume);
         
         if(!OrderSend(request, result))
         {
            Print("Close position failed: ", GetLastError());
            return;
         }
         
         if(result.retcode == TRADE_RETCODE_DONE)
         {
            Print("Position closed successfully!");
         }
         else
         {
            Print("Close position failed. Retcode: ", result.retcode);
         }
      }
   }
}

//+------------------------------------------------------------------+