//+------------------------------------------------------------------+
//|                                                   EMA_Cross.mq5 |
//|                                      Generated by DeepSeek AI    |
//+------------------------------------------------------------------+
#property copyright "DeepSeek AI"
#property version   "1.00"
#property description "EMA Crossover with OpenCL optimization"

//--- Input parameters
input int                 InpFastEMA = 12;     // Fast EMA Period
input int                 InpSlowEMA = 26;     // Slow EMA Period
input double              InpLotSize = 0.1;    // Lot Size
input int                 InpStopLoss = 200;   // Stop Loss (points)
input int                 InpTakeProfit = 400; // Take Profit (points)
input bool                InpUseOpenCL = true; // Enable OpenCL acceleration

//--- Global variables (non-constant)
bool                      UseOpenCL;           // Internal OpenCL flag

//--- OpenCL variables
int                       clContext;           // OpenCL context handle
int                       clProgram;           // OpenCL program handle
int                       clKernel;            // OpenCL kernel handle
int                       clBufferPrices;      // Buffer for prices
int                       clBufferFastEMA;     // Buffer for fast EMA
int                       clBufferSlowEMA;     // Buffer for slow EMA

//--- Indicators handles
int                       fastEMAHandle;
int                       slowEMAHandle;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    //--- Copy input parameter to modifiable variable
    UseOpenCL = InpUseOpenCL;
    
    //--- Initialize indicators
    fastEMAHandle = iMA(_Symbol, _Period, InpFastEMA, 0, MODE_EMA, PRICE_CLOSE);
    slowEMAHandle = iMA(_Symbol, _Period, InpSlowEMA, 0, MODE_EMA, PRICE_CLOSE);
    
    if(fastEMAHandle == INVALID_HANDLE || slowEMAHandle == INVALID_HANDLE)
    {
        Print("Error creating indicators");
        return INIT_FAILED;
    }
    
    //--- Initialize OpenCL if enabled
    if(UseOpenCL)
    {
        if(!InitializeOpenCL())
        {
            Print("OpenCL initialization failed, using CPU calculations");
            UseOpenCL = false;
        }
    }
    
    return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Initialize OpenCL environment                                    |
//+------------------------------------------------------------------+
bool InitializeOpenCL()
{
    //--- Create OpenCL context
    clContext = CLContextCreate();
    if(clContext == INVALID_HANDLE)
    {
        Print("Failed to create OpenCL context");
        return false;
    }
    
    //--- OpenCL source code for EMA calculation
    string clSource = 
    "__kernel void calculateEMA(__global const double *prices, " +
    "                          __global double *fastEMA, " +
    "                          __global double *slowEMA, " +
    "                          int fastPeriod, " +
    "                          int slowPeriod, " +
    "                          double fastAlpha, " +
    "                          double slowAlpha, " +
    "                          int rates_total) " +
    "{ " +
    "    int i = get_global_id(0); " +
    "    " +
    "    if(i >= rates_total) return; " +
    "    " +
    "    // Calculate fast EMA" +
    "    if(i == 0) " +
    "        fastEMA[i] = prices[i]; " +
    "    else " +
    "        fastEMA[i] = prices[i] * fastAlpha + fastEMA[i-1] * (1 - fastAlpha); " +
    "    " +
    "    // Calculate slow EMA" +
    "    if(i == 0) " +
    "        slowEMA[i] = prices[i]; " +
    "    else " +
    "        slowEMA[i] = prices[i] * slowAlpha + slowEMA[i-1] * (1 - slowAlpha); " +
    "} ";
    
    //--- Create program
    clProgram = CLProgramCreate(clContext, clSource);
    if(clProgram == INVALID_HANDLE)
    {
        Print("Failed to create OpenCL program");
        CLContextFree(clContext);
        clContext = INVALID_HANDLE;
        return false;
    }
    
    //--- Create kernel
    clKernel = CLKernelCreate(clProgram, "calculateEMA");
    if(clKernel == INVALID_HANDLE)
    {
        Print("Failed to create OpenCL kernel");
        CLProgramFree(clProgram);
        CLContextFree(clContext);
        clProgram = INVALID_HANDLE;
        clContext = INVALID_HANDLE;
        return false;
    }
    
    return true;
}

//+------------------------------------------------------------------+
//| Calculate EMA using OpenCL                                       |
//+------------------------------------------------------------------+
bool CalculateEMAOpenCL(double &fastEMA[], double &slowEMA[], int rates_total)
{
    //--- Prepare data
    double prices[];
    ArrayResize(prices, rates_total);
    
    //--- Copy close prices
    if(CopyClose(_Symbol, _Period, 0, rates_total, prices) != rates_total)
    {
        Print("Failed to copy price data");
        return false;
    }
    
    //--- Create buffers
    clBufferPrices = CLBufferCreate(clContext, rates_total * sizeof(double), CL_MEM_READ_ONLY);
    if(clBufferPrices == INVALID_HANDLE)
    {
        Print("Failed to create price buffer");
        return false;
    }
    
    clBufferFastEMA = CLBufferCreate(clContext, rates_total * sizeof(double), CL_MEM_READ_WRITE);
    if(clBufferFastEMA == INVALID_HANDLE)
    {
        Print("Failed to create fast EMA buffer");
        CLBufferFree(clBufferPrices);
        return false;
    }
    
    clBufferSlowEMA = CLBufferCreate(clContext, rates_total * sizeof(double), CL_MEM_READ_WRITE);
    if(clBufferSlowEMA == INVALID_HANDLE)
    {
        Print("Failed to create slow EMA buffer");
        CLBufferFree(clBufferPrices);
        CLBufferFree(clBufferFastEMA);
        return false;
    }
    
    //--- Write data to buffers
    if(!CLBufferWrite(clBufferPrices, prices, 0, rates_total * sizeof(double)))
    {
        Print("Failed to write to price buffer");
        CLBufferFree(clBufferPrices);
        CLBufferFree(clBufferFastEMA);
        CLBufferFree(clBufferSlowEMA);
        return false;
    }
    
    //--- Set kernel arguments
    if(!CLSetKernelArgMem(clKernel, 0, clBufferPrices) ||
       !CLSetKernelArgMem(clKernel, 1, clBufferFastEMA) ||
       !CLSetKernelArgMem(clKernel, 2, clBufferSlowEMA) ||
       !CLSetKernelArg(clKernel, 3, InpFastEMA) ||
       !CLSetKernelArg(clKernel, 4, InpSlowEMA) ||
       !CLSetKernelArg(clKernel, 5, 2.0 / (InpFastEMA + 1)) ||
       !CLSetKernelArg(clKernel, 6, 2.0 / (InpSlowEMA + 1)) ||
       !CLSetKernelArg(clKernel, 7, rates_total))
    {
        Print("Failed to set kernel arguments");
        CLBufferFree(clBufferPrices);
        CLBufferFree(clBufferFastEMA);
        CLBufferFree(clBufferSlowEMA);
        return false;
    }
    
    //--- Execute kernel
    uint workOffset[] = {0};
    uint workSize[] = {(uint)rates_total};
    
    if(!CLExecute(clKernel, 1, workOffset, workSize))
    {
        Print("Failed to execute OpenCL kernel");
        CLBufferFree(clBufferPrices);
        CLBufferFree(clBufferFastEMA);
        CLBufferFree(clBufferSlowEMA);
        return false;
    }
    
    //--- Read results
    if(!CLBufferRead(clBufferFastEMA, fastEMA, 0, rates_total * sizeof(double)) ||
       !CLBufferRead(clBufferSlowEMA, slowEMA, 0, rates_total * sizeof(double)))
    {
        Print("Failed to read results from buffers");
        CLBufferFree(clBufferPrices);
        CLBufferFree(clBufferFastEMA);
        CLBufferFree(clBufferSlowEMA);
        return false;
    }
    
    //--- Cleanup buffers
    CLBufferFree(clBufferPrices);
    CLBufferFree(clBufferFastEMA);
    CLBufferFree(clBufferSlowEMA);
    
    return true;
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    //--- Check for minimum bars
    if(Bars(_Symbol, _Period) < MathMax(InpFastEMA, InpSlowEMA) + 1)
        return;
    
    //--- Get EMA values
    double fastEMA[], slowEMA[];
    int rates_total = Bars(_Symbol, _Period);
    
    if(UseOpenCL && clContext != INVALID_HANDLE)
    {
        //--- Use OpenCL calculation
        ArrayResize(fastEMA, rates_total);
        ArrayResize(slowEMA, rates_total);
        
        if(!CalculateEMAOpenCL(fastEMA, slowEMA, rates_total))
        {
            // Fallback to standard indicators if OpenCL fails
            if(!GetEMAValues(fastEMA, slowEMA))
                return;
        }
    }
    else
    {
        //--- Use standard indicator calculation
        if(!GetEMAValues(fastEMA, slowEMA))
            return;
    }
    
    ArraySetAsSeries(fastEMA, true);
    ArraySetAsSeries(slowEMA, true);
    
    //--- Check for crossover signals
    CheckForSignal(fastEMA, slowEMA);
}

//+------------------------------------------------------------------+
//| Get EMA values from indicators                                   |
//+------------------------------------------------------------------+
bool GetEMAValues(double &fastEMA[], double &slowEMA[])
{
    if(CopyBuffer(fastEMAHandle, 0, 0, 3, fastEMA) != 3)
    {
        Print("Failed to copy fast EMA values");
        return false;
    }
    
    if(CopyBuffer(slowEMAHandle, 0, 0, 3, slowEMA) != 3)
    {
        Print("Failed to copy slow EMA values");
        return false;
    }
    
    return true;
}

//+------------------------------------------------------------------+
//| Check for crossover signals                                      |
//+------------------------------------------------------------------+
void CheckForSignal(double &fastEMA[], double &slowEMA[])
{
    //--- Check for BUY signal (fast crosses above slow)
    if(fastEMA[1] <= slowEMA[1] && fastEMA[0] > slowEMA[0])
    {
        CloseAllPositions();
        OpenPosition(ORDER_TYPE_BUY);
    }
    //--- Check for SELL signal (fast crosses below slow)
    else if(fastEMA[1] >= slowEMA[1] && fastEMA[0] < slowEMA[0])
    {
        CloseAllPositions();
        OpenPosition(ORDER_TYPE_SELL);
    }
}

//+------------------------------------------------------------------+
//| Open position                                                    |
//+------------------------------------------------------------------+
void OpenPosition(ENUM_ORDER_TYPE orderType)
{
    MqlTradeRequest request = {};
    MqlTradeResult result = {};
    
    request.action = TRADE_ACTION_DEAL;
    request.symbol = _Symbol;
    request.volume = NormalizeDouble(InpLotSize, 2);
    request.type = orderType;
    request.type_filling = ORDER_FILLING_FOK;
    request.deviation = 10;
    
    //--- Calculate SL and TP
    double price = SymbolInfoDouble(_Symbol, 
        (orderType == ORDER_TYPE_BUY) ? SYMBOL_ASK : SYMBOL_BID);
    
    if(InpStopLoss > 0)
    {
        request.sl = (orderType == ORDER_TYPE_BUY) ? 
            price - InpStopLoss * _Point : 
            price + InpStopLoss * _Point;
        request.sl = NormalizeDouble(request.sl, _Digits);
    }
    
    if(InpTakeProfit > 0)
    {
        request.tp = (orderType == ORDER_TYPE_BUY) ? 
            price + InpTakeProfit * _Point : 
            price - InpTakeProfit * _Point;
        request.tp = NormalizeDouble(request.tp, _Digits);
    }
    
    //--- Send order with proper return value checking
    bool orderSent = OrderSend(request, result);
    
    if(!orderSent)
    {
        Print("OrderSend failed. Error code: ", GetLastError());
        Print("Retcode: ", result.retcode, 
              ", Deal: ", result.deal,
              ", Order: ", result.order,
              ", Volume: ", result.volume,
              ", Price: ", result.price,
              ", Bid: ", result.bid,
              ", Ask: ", result.ask);
    }
    else if(result.retcode != TRADE_RETCODE_DONE)
    {
        Print("Order not executed. Retcode: ", result.retcode,
              ", Deal: ", result.deal,
              ", Order: ", result.order);
    }
    else
    {
        Print("Order executed successfully. Ticket: ", result.order,
              ", Price: ", result.price,
              ", Volume: ", result.volume);
    }
}

//+------------------------------------------------------------------+
//| Close all positions                                              |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket > 0 && PositionGetString(POSITION_SYMBOL) == _Symbol)
        {
            MqlTradeRequest request = {};
            MqlTradeResult result = {};
            
            request.action = TRADE_ACTION_DEAL;
            request.symbol = _Symbol;
            request.volume = PositionGetDouble(POSITION_VOLUME);
            request.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? 
                ORDER_TYPE_SELL : ORDER_TYPE_BUY;
            request.position = ticket;
            request.type_filling = ORDER_FILLING_FOK;
            
            //--- Send close order with return value checking
            bool orderSent = OrderSend(request, result);
            
            if(!orderSent)
            {
                Print("Failed to close position. Ticket: ", ticket, 
                      ", Error: ", GetLastError());
            }
            else if(result.retcode != TRADE_RETCODE_DONE)
            {
                Print("Position close not executed. Ticket: ", ticket,
                      ", Retcode: ", result.retcode);
            }
        }
    }
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    //--- Cleanup OpenCL
    if(clKernel != INVALID_HANDLE)
    {
        CLKernelFree(clKernel);
        clKernel = INVALID_HANDLE;
    }
    
    if(clProgram != INVALID_HANDLE)
    {
        CLProgramFree(clProgram);
        clProgram = INVALID_HANDLE;
    }
    
    if(clContext != INVALID_HANDLE)
    {
        CLContextFree(clContext);
        clContext = INVALID_HANDLE;
    }
    
    //--- Release indicators
    if(fastEMAHandle != INVALID_HANDLE)
    {
        IndicatorRelease(fastEMAHandle);
        fastEMAHandle = INVALID_HANDLE;
    }
    
    if(slowEMAHandle != INVALID_HANDLE)
    {
        IndicatorRelease(slowEMAHandle);
        slowEMAHandle = INVALID_HANDLE;
    }
    
    //--- Clear global variables
    UseOpenCL = false;
}